Fabrication de la racine. prototype de script à debugguer

diff --git a/scripts/Mkinitramfs/live b/scripts/Mkinitramfs/live
--- a/scripts/Mkinitramfs/live
+++ b/scripts/Mkinitramfs/live
@@ -6,8 +6,9 @@
 # Return value: indicates if root is mount
 
 RAMSIZE=1000000
-ISN_DIR=isnbs
+ISN_DIR=isnfs
 ISN_NAME=base
+ISN_USER=live
 LISTE_EXTENSIONS=extensions_${ISN_NAME}
 MARQUEUR=${ISN_DIR}/${ISN_NAME}
 # if BRUTAL then even unknown FS are tested (sometimes this abruti doesn't known
@@ -15,7 +16,8 @@ MARQUEUR=${ISN_DIR}/${ISN_NAME}
 BRUTAL=Yes
 DEBUG=Yes
 
-MONTAGE=/tmp/__tempo_isn
+BASEROOT=/ISN
+MONTAGE=/cdrom
 
 get_fstype ()
 {
@@ -135,35 +137,246 @@ pre_mountroot()
     fi
 }
 
+
+mount_base()
+{
+    FSTYPE=$(get_fstype "$1")
+    if [ -z "$FSTYPE" ] ; then
+	mount $1 $MONTAGE
+    else
+	mount -t $FSTYPE $1 $MONTAGE
+    fi
+    mount ${MONTAGE}/${ISN_DIR}/${ISN_NAME} $BASEROOT -t squashfs -o loop
+}
+
+
+
 mountroot()
 {
     pre_mountroot
+
+    mount_agreg ${ROOT}
+# on test l'existence du répertoire /boot sur l'arborescence montée
+    if [ -d ${BASEROOT}/boot
+    then
+# on enchaine sur le script de ClefAgreg    
+# Enable kernel messages
+	echo "6" > /proc/sys/kernel/printk
     
-	# Get the root filesystem type if not set
-    if [ -z "${ROOTFSTYPE}" ]; then
-	FSTYPE=$(get_fstype "${ROOT}")
-	else
-		FSTYPE=${ROOTFSTYPE}
+# Set paths
+	echo -n "Setting paths..."
+	PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:."
+	export PATH    
+   
+# on vide la table de hashage 
+	hash -r
+	
+	FOUNDMEM="$(awk '/MemTotal/{print $2}' /proc/meminfo)"
+	TOTALMEM="$(awk 'BEGIN{m=0};/MemFree|Cached/{m+=$2};END{print m}' /proc/meminfo)"
+	
+# FOUNDMEM = taille RAM totale, TOTALMEM = taille RAM disponible
+	
+# Minimum size of additional ram partitions (vient de Knoppix)
+	MINSIZE=2000
+# At least this much memory minus 30% should remain when home and var are full.
+	MINLEFT=16000
+# Maximum ramdisk size
+	MAXSIZE="$(expr $TOTALMEM - $MINLEFT)"
+# Default ramdisk size for ramdisk
+	RAMSIZE="$(expr $TOTALMEM / 5)"
+	RAMSIZE=$(expr $RAMSIZE \* 4)
+	mkdir -p /ramdisk
+# tmpfs/varsize version, can use swap
+	echo -n "Creating /ramdisk dynamic size=${RAMSIZE}k on shared memory..."
+	mount -t tmpfs -o "size=${RAMSIZE}k" /ramdisk /ramdisk
+	echo "Done."
+
+	mkdir -p /ramdisk/home/
+# incomplet, on oublie une partie des modifications avec les extensions
+    
+# Create empty utmp and wtmp
+    :> /ramdisk/var/run/utmp
+    :> /ramdisk/var/run/wtmp
+
+# on recopie la ligne de commande
+    echo $CMDLINE > /ramdisk/etc/cmdlineboot
+    touch /ramdisk/etc/resolv.conf
+    
+# Extremely important, init crashes on shutdown if this is only a link
+
+    df
+    echo "...RAMDISK fini."
+    
+# Mis en place du modprobe au cas où
+# bon le unionfs
+
+    echo "/sbin/modprobe" > /proc/sys/kernel/modprobe
+    
+    
+    echo "Initialisation du système"
+    mkdir -p ${rootmnt}
+    cd /
+    mount -t aufs aufs ${rootmnt} -o dirs=/ramdisk=rw:/${BASEROOT}=ro
+    
+# le pivot root ne marche pas ici scrogneugneu, usage de run-init
+    
+    mkdir ${rootmnt}/oldroot
+    cd ${rootmnt}
+    
+# recherche d'une extension
+#
+# TODO: Prise en compte de la fin de l'extension pour hierarchiser
+# le chargement des extensions. Bon, dans un premier temps pas urgent
+# chargement donné soit par un fichier ordre_extensions, soit par
+# date du plus vieux au plus récent.
+#
+    RAJOUT=""
+    INDICE=1
+    if [ -f ${MONTAGE}/ordre_extensions ] ; then
+	LISTE_EXT=`cat ${MONTAGE}/ordre_extensions | sed -e 's|^|${MONTAGE}/${ISN_DIR}/|'`
+    else
+	LISTE_EXT=`ls -tr ${MONTAGE}/${ISN_DIR}/extension*.sqh`
+    fi
+    for fichier in $LISTE_EXT ; do
+	if [ ! -b /dev/loop$INDICE ] ; then
+	    cd /dev
+	    mknod loop$INDICE b 7 $INDICE
+	    cd ${rootmnt}
 	fi
+	INDICE=`expr $INDICE + 1`
+	DIR=`echo $fichier | sed -e 's/^.*\(extension.*\).sqh/\1/'`
+	echo Installation de $DIR
+	mkdir -p /$DIR
+	mount $fichier /$DIR -t squashfs -o loop
+	RAJOUT=:/$DIR=ro+wh$RAJOUT
+    done
+    
+# recherche extension externe
+# À voir dans un deuxième temps
+#    mkdir -p /extensions
+#    if /bin/trouvefichier UIS /extensions $LISTE_EXTENSIONS ; then
+#	for fichier in `cat /extensions/$LISTE_EXTENSIONS` ; do
+##while [ -f ${MONTAGE}/${ISN_DIR}/extension$NUMERO.sqh ] ; do
+#	    if [ ! -b /dev/loop$INDICE ] ; then
+#		cd /dev
+#		mknod loop$INDICE b 7 $INDICE
+#		cd ${rootmnt}
+#	    fi
+#	    INDICE=`expr $INDICE + 1`
+#	    DIR=`echo $fichier | sed -e 's/^.*\(extension.*\).sqh/\1/'`
+#	    echo Installation de $DIR
+#	    mkdir -p /$DIR
+#	    mount /extensions/$ISN_DIR/$fichier /$DIR -t squashfs -o loop
+#	    RAJOUT=:/$DIR=ro+wh$RAJOUT
+#	done
+#    fi
+    umount /dev/pts
+    mv /dev /ramdisk
+    ln -s /ramdisk/dev /dev
+    echo Assemblage des repertoires
+    mount -t aufs aufs ${rootmnt} -o dirs=/ramdisk=rw$RAJOUT:/${BASEROOT}=ro
+    if [ ! -d ${rootmnt}/oldroot ] ; then
+	mkdir ${rootmnt}/oldroot
+    fi
+    if [ ! -d ${rootmnt}/proc ] ; then 
+	mkdir ${rootmnt}/proc
+    fi
+    if [ ! -d ${rootmnt}/sys ] ; then
+	mkdir ${rootmnt}/sys
+    fi
+    echo Fabrication de /home/${ISN_USER}
 
-	[ "$quiet" != "y" ] && log_begin_msg "Running /scripts/local-premount"
-	run_scripts /scripts/local-premount
-	[ "$quiet" != "y" ] && log_end_msg
+# mis à jour de /home/${ISN_USER}
+# (cd ${rootmnt}/etc/skel ; tar c .) | (cd /ramdisk/home/${ISN_USER} ; tar x)
 
-	if [ "${readonly}" = "y" ]; then
-		roflag=-r
-	else
-		roflag=-w
+    if [ -f ${MONTAGE}/home.tar.bfe ] ; then
+
+# cas d'un cryptage
+
+	PASSWD=`cat /proc/cmdline | grep clefcodage | sed -e 's/^.*clefcodage="\(.*\)".*$/\1/'`
+	if [ ! -z $PASSWD ] ; then 
+	    echo $PASSWD > /ramdisk/home/.clefcodage
 	fi
+	if [ -f ${MONTAGE}/clavier.kmap.gz ] ; then
+	    loadkeys ${MONTAGE}/clavier.kmap.gz
+	fi
+	cd /ramdisk/home
+	cp ${MONTAGE}/home.tar.bfe .
+	bcrypt home.tar.bfe
+	tar xf home.tar
+	rm home.tar
+	mkdir -p /ramdisk/home/${ISN_USER}/public
+	cd ${MONTAGE}/home
+	cp -a . /ramdisk/home/${ISN_USER}/public
+	cd  /ramdisk/home/${ISN_USER}/public
+	if [ -f ${MONTAGE}/droitshome.txt ] ; then
+	    cp ${MONTAGE}/droitshome.txt /tmp
+	    chmod +x /tmp/droitshome.txt
+	    /tmp/droitshome.txt
+	    rm /tmp/droitshome.txt
+	fi
+	if [ -f ${MONTAGE}/liens.cpio ] ; then
+	    cpio -i < ${MONTAGE}/liens.cpio
+	fi
+    else
 
-	# FIXME This has no error checking
-	modprobe ${FSTYPE}
+# cas normal
 
-	# FIXME This has no error checking
-	# Mount root
-	mount ${roflag} -t ${FSTYPE} ${ROOTFLAGS} ${ROOT} ${rootmnt}
-
-	[ "$quiet" != "y" ] && log_begin_msg "Running /scripts/local-bottom"
-	run_scripts /scripts/local-bottom
-	[ "$quiet" != "y" ] && log_end_msg
+	cd  /ramdisk/home/${ISN_USER}
+	if [ ! -f ${MONTAGE}/home/.perso ] ; then
+	    cp -a ${rootmnt}/etc/skel/. .
+	fi
+# (cd ${MONTAGE}/home ; tar c .) | (cd /ramdisk/home/${ISN_USER} ; tar x)
+	cd ${MONTAGE}/home
+	cp -a . /ramdisk/home/${ISN_USER}
+	cd  /ramdisk/home/${ISN_USER}
+	if [ -f ${MONTAGE}/droitshome.txt ] ; then
+	    cp ${MONTAGE}/droitshome.txt /tmp
+	    chmod +x /tmp/droitshome.txt
+	    /tmp/droitshome.txt
+	    rm /tmp/droitshome.txt
+	fi
+	if [ -f ${MONTAGE}/liens.cpio ] ; then
+	    cpio -i < ${MONTAGE}/liens.cpio
+	fi
+    fi
+    cd /
+#chroot ${rootmnt} chmod -R +w /home/${ISN_USER}
+#chroot ${rootmnt} chown -R live /home/${ISN_USER}/
+    chmod -R +w /ramdisk/home/${ISN_USER}
+    chown -R 1000.1000 /ramdisk/home/${ISN_USER}/
+# on conserve des liens vers les systèmes de fichiers séparés
+# fait par init
+#    chroot ${rootmnt} mount /proc
+#    chroot ${rootmnt} mount /sys
+    mkdir -p ${rootmnt}/oldroot/ramdisk
+    mount -o bind /ramdisk ${rootmnt}/oldroot/ramdisk
+    mkdir -p ${rootmnt}/oldroot${MONTAGE}
+    mount -o bind ${MONTAGE} ${rootmnt}/oldroot${MONTAGE}
+    for dir in `ls -d /extension*` ; do
+	if [ -d /$dir ] ; then
+	    mkdir -p ${rootmnt}/oldroot/$dir
+	    mount -o bind /$dir ${rootmnt}/oldroot/$dir
+	fi
+    done
+# inutile d'après init
+#    umount /proc/bus/usb
+#    umount /proc
+#    umount /sys
+    echo RAMDISK fini, boot normal.
+    echo Running init
+    cd /
+else
+    echo "Aie, big panic, cannot find a valid root filesystem.."
+    echo "Here is a shell, enjoy!"
+    PS1="${ISN_USER}# "
+    export PS1
+    echo "6" > /proc/sys/kernel/printk
+# Allow signals
+    trap 1 2 3 15
+    exec /bin/sh
+fi
+    [ "$quiet" != "y" ] && log_begin_msg "Running /scripts/live-bottom"
+    run_scripts /scripts/live-bottom
+    [ "$quiet" != "y" ] && log_end_msg
 }
